#!/bin/bash
# Generate SeaweedFS config files from .env values.
# Run BEFORE `docker compose up` so the bind-mounted configs contain real secrets.
# Usage: bash scripts/init-seaweedfs-config.sh [env_file]
#   env_file: path to .env file (default: .env in project root)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${1:-$PROJECT_ROOT/.env}"
CONFIG_DIR="$PROJECT_ROOT/seaweedfs-config"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env file not found at $ENV_FILE" >&2
  exit 1
fi

# Source env vars (only the ones we need)
source <(grep -E "^(SEAWEED_S3_ACCESS_KEY|SEAWEED_S3_SECRET_KEY)=" "$ENV_FILE" 2>/dev/null || true)

# Generate s3-config.json
cat > "$CONFIG_DIR/s3-config.json" << JSONEOF
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "${SEAWEED_S3_ACCESS_KEY:-seaweedadmin}",
          "secretKey": "${SEAWEED_S3_SECRET_KEY:-^seaweedadmin!changeme!}"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "Write"
      ]
    }
  ]
}
JSONEOF

# Source env vars for JWT keys (use same key for all three if SEAWEED_JWT_SIGNING_KEY is set)
source <(grep -E "^(SEAWEED_JWT_SIGNING_KEY|SEAWEED_FILER_SIGNING_KEY|SEAWEED_MASTER_SIGNING_KEY)=" "$ENV_FILE" 2>/dev/null || true)
JWT_KEY="${SEAWEED_JWT_SIGNING_KEY:-change_me_seaweed_jwt_key}"
FILER_KEY="${SEAWEED_FILER_SIGNING_KEY:-$JWT_KEY}"
MASTER_KEY="${SEAWEED_MASTER_SIGNING_KEY:-$JWT_KEY}"

# Generate security.toml
cat > "$CONFIG_DIR/security.toml" << TMLEOF
# SeaweedFS Security Configuration
# Generated by init-seaweedfs-config.sh — do not edit directly.

[jwt.signing]
key = "${JWT_KEY}"

[jwt.filer_signing]
key = "${FILER_KEY}"

[jwt.master_signing]
key = "${MASTER_KEY}"

[access]
# Require authentication for all access
ui = true
TMLEOF

echo "[init-seaweedfs-config] Generated $CONFIG_DIR/s3-config.json"
echo "[init-seaweedfs-config] Generated $CONFIG_DIR/security.toml"
